### ISSUE TITLE
Explain module

### ISSUE THREAD

**Issue by Hongarc** [ehmicky/human-exit-code#1]
Why return a string instead of a number is human-friendly?

Please help me understand the purpose of this module.

Thank you.

**Comment by ehmicky** [comment]
Hi @Hongarc, thanks a lot for your enthusiasm :)
I just created this repository, not done yet.

It returns a human-friendly description of an exit code. E.g. `0` -> `"Success"`

**Comment by ehmicky** [comment]
The package documentation is now done.
